version: "3"
services:
    client:
        container_name: "client"
        build:
            context: .
            dockerfile: Dockerfile
        command: bash
        stdin_open: true
        tty: true
