version: "3"

services:
  ctfd:
    image: ctfd/ctfd
    restart: always
    ports:
      - "8000:8000"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1105:5000"
    volumes:
      - .:/server
    command: python3 -m flask run --host=0.0.0.0
