#!/bin/bash

# Timezone 변경
ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# ubuntu update
apt update && apt upgrade -y

# 필요 패키지 설치
apt install git sqlite3 python3 python3-pip -y

# 필요 python 패키지 설치
pip3 install flask, json, sqlite3

# docker 설치
apt install ca-certificates curl gnupg lsb-release -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# docker update
apt update -y

# docker engine 설치
apt install docker-ce docker-ce-cli containerd.io -y

# docker-compose 설치
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose